name: Windows RDP

on:
  workflow_dispatch: # Trigger manually or adjust as needed

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Add User
        run: |
          net user /add myuser 1sampai8*
          net localgroup administrators myuser /add

      - name: Enable Remote Desktop
        run: |
          powershell -Command "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server' -Name 'fDenyTSConnections' -Value 0"
          powershell -Command "Get-NetFirewallRule -DisplayGroup 'Remote Desktop' | Set-NetFirewallRule -Enabled True"

      - name: Display IP Address
        run: systeminfo | findstr /C:"IPv4 Address"

      - name: Keep Runner Alive
        run: timeout /t 99999
